# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

fortune | cowsay

# Set name of the theme to load
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="aussiegeek"
#ZSH_THEME="random" # crazy mode
#pygmalion
 ZSH_THEME="ajduke"
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=30

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/dotfiles/zshell

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git brew git-extras history jsontools lol osx redis-cli npm)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='nano'


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"


# Load aliases
if [ -f ~/dotfiles/bash/shell_aliases ]; then
  source ~/dotfiles/bash/shell_aliases
fi

if [ -f ~/dotfiles/bash/shell_functions.sh ]; then
  source ~/dotfiles/bash/shell_functions.sh
fi


# export PATH=$PATH:$PWD/node_modules/.bin
# adds the brew python home installation
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# adds the python bin dir for the avaiable executables 
export PATH="~/Library/Python/3.7/bin:$PATH" 

# Load zsh-syntax-highlighting.

# Load zsh-syntax-highlighting.
# Load zsh-syntax-highlighting.

# source ~/dotfiles/zshell/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# Load zsh-autosuggestions.
# source ~/dotfiles/zshell/zsh-autosuggestions/zsh-autosuggestions.zsh


ZSH_DISABLE_COMPFIX=true
# source ~/dotfiles/git/gitbash.sh

# Adding the binarioes to the path for easy access

export PATH="/usr/local/opt/mongodb-community@3.4/bin:$PATH"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH=/Users/abhijeetsutar/.gem/ruby/2.7.0p0/bin:/usr/local/opt/ruby/bin:/Users/abhijeetsutar/.yarn/bin:/Users/abhijeetsutar/.config/yarn/global/node_modules/.bin:/usr/local/opt/mongodb-community@3.4/bin:/Users/abhijeetsutar/.nvm/versions/node/v10.16.0/bin:~/Library/Python/3.7/bin:/usr/local/opt/python/libexec/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
export PATH=/usr/local/lib/ruby/gems/2.7.0p0/bin:$PATH
export EJSON_KEYDIR=$HOME/.ejson

export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_SDK/emulator:$ANDROID_SDK/tools:$PATH
export PATH=$ANDROID_SDK/tools/bin:$PATH
export ANDROID_HOME=~/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH=$PATH:/home/abhijeet/apps-tools/phantomjs-1.9.7/bin:~/apps-tools/smartgithg-5_0_9/bin:./node_modules
export PATH="/usr/local/opt/openjdk/bin:$PATH"
export PATH=".rvm/gems/ruby-2.7.2/bin":$PATH
# echo 'export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.7.0/bin:$PATH"' >> ~/.zshrc

if [ -z "$LANG" ]; then export LANG="$(defaults read -g AppleLocale | sed 's/@.*$//g').UTF-8"; fi

# export LANG="en_US.UTF-8"


if [ -f ~/.nvm/nvm.sh ]; then
  source ~/.nvm/nvm.sh
  nvm use default
else
  echo 'No nvm Installation found'
fi
